### PR TITLE
Created opcode list (incomplete)

### PR DESCRIPTION
**Pull request by lugaxker**

### CODE REVIEW

**Comment by dagurval** [comment]
Looks good to me. The only reason I still occasionally visit the bitcoin.it wiki is for the OP code list, so glad to see this contribution

**Comment by lugaxker** [comment]
Thanks I'll try to complete this list later.

**Comment by dagurval** [comment]
The remaining work from Verde was merged and caused this PR to conflict. Do you think you'll be wanting to merge your changes?

**Comment by dagurval** [comment]
I handled the merge conflict and merged your changes, thanks again!

**Comment by lugaxker** [comment]
Hi, I didn't have time to do this sorry. Besides, I am not familiar with merging so I didn't really know how to.

Thank you.

As I said I'll try to complete the list using the bitcoin.it wiki.

**Comment by dagurval** [comment]
I’ll just handle any merge conflicts from now. Content is the most difficult task here :-)

Btw, I did few of the crypto op codes here https://github.com/BitcoinUnlimited/BitcoinCashSpecification/pull/11

**Pull request merged**
